### PR TITLE
OCPBUGS-28597: Disable cluster-olm-operator

### PR DESCRIPTION
**Pull request by kevinrizza**
Temporarily disable this component while upgrading rukpak with a breaking change

### CODE REVIEW

**Review by grokspawn — APPROVED** [review]

**Comment by grokspawn** [comment]
Re-title commit in the form "UPSTREAM: <drop>:" ?

**Comment by kuiwang02** [comment]
wait @jianzhangbjz to add qe-approved

**Comment by kevinrizza** [comment]
this looks like cluster init problems. trying again.

/retest

**Pull request merged**
