### PR TITLE
NO-ISSUE: Adding permissions for mutatingwebhookconfigurations

### PR DESCRIPTION
**Pull request by itroyano**
https://redhat-internal.slack.com/archives/GHMALGJV6/p1726024937655169

### CODE REVIEW

**Comment by bentito** [comment]
ties back to change in upstream:

https://github.com/operator-framework/catalogd/blob/074ec55052717371e01c20c3351ede2e984e44d5/config/base/manager/webhook/manifests.yaml

**Review by bentito — APPROVED** [review]

**Review by perdasilva — APPROVED** [review]

**Comment by perdasilva** [comment]
@itroyano please add NO-ISSUE: to the title (or create a bug =D)

**Comment by perdasilva** [comment]
Gonna unhold - I think we need this to get the re-enable PR to pass:

```
message: "CatalogdStaticResourcesDegraded: \"catalogd/16-mutatingwebhookconfiguration-catalogd-mutating-webhook-configuration.yml\" (string): mutatingwebhookconfigurations.admissionregistration.k8s.io \"catalogd-mutating-webhook-configuration\" is forbidden: User \"system:serviceaccount:openshift-cluster-olm-operator:cluster-olm-operator\" cannot get resource \"mutatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope\nCatalogdStaticResourcesDegraded: "
```

Getting these errors in the e2e run

**Pull request merged**
