### PR TITLE
OPRUN-3588: Add OLMv1 capability annotation to manifests

### PR DESCRIPTION
**Pull request by perdasilva**
Adds OLMv1 annotation to manifests

### CODE REVIEW

**Comment by tmshort** [comment]
Appears that none of the manifests were applied.

**Comment by tmshort** [comment]
ci/prow/openshift-e2e-aws-techpreview is going to fail until https://github.com/openshift/origin/pull/29283 is merged

**Comment by joelanford** [comment]
/hold 

I used a `replace` in `go.mod` to get early CI signal on the `openshift/api` update from https://github.com/openshift/api/pull/2097

**Pull request merged**
