### PR TITLE
NO-ISSUE: Bump operator-controller and catalogd dependencies to v1.0.0-rc1

### PR DESCRIPTION
**Pull request by everettraven**
## Description
Bumps the `github.com/operator-framework/operator-controller` and `github.com/operator-framework/catalogd` dependencies to v1.0.0-rc1 so that our clients now use the v1 ClusterExtension and ClusterCatalog APIs.

### CODE REVIEW

**Review by tmshort — APPROVED** [review]
/lgtm

**Review by LalatenduMohanty — APPROVED** [review]

**Comment by tmshort** [comment]
There are still references to v1alpha1 in:
https://github.com/openshift/cluster-olm-operator/blob/main/pkg/controller/dynamicrequiredmanifest_controller_test.go

But ci/prow/unit is passing?

**Comment by everettraven** [comment]
@tmshort I believe I changed that here: https://github.com/openshift/cluster-olm-operator/pull/84/files#diff-548f7da820e8bb4ebeb0625bb650711b200e56b4d49979deb25199b4abd40ddaR16

**Comment by tmshort** [comment]
See: https://github.com/openshift/cluster-olm-operator/blob/3572b28648dec161c3405033a14f38d1668b1e07/pkg/controller/dynamicrequiredmanifest_controller_test.go#L191

**Pull request merged**
