### PR TITLE
OPRUN-3605: pkg/clients: correctly handle setting lastTransitionTime

### PR DESCRIPTION
**Pull request by joelanford**
Updated based on implementation of dynamic operator client in library-go: https://github.com/openshift/library-go/blob/9b8048fbe583871efecdc12c0ed536677abb4440/pkg/operator/genericoperatorclient/dynamic_operator_client.go#L282-L380

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by grokspawn** [comment]
Sorry about the cherry-pick.  Wrong tab!

**Comment by grokspawn** [comment]
/retitle OPRUN-3605: pkg/clients: correctly handle setting lastTransitionTime

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by joelanford** [comment]
/override ci/prow/openshift-e2e-aws-techpreview

Failures are unrelated to this change

**Pull request merged**
