### PR TITLE
OCPBUGS-32188: Update README.md

### PR DESCRIPTION
**Pull request by bentito**
Adds more context about what this repo is for.

### CODE REVIEW

**Review by m1kola — APPROVED** [review]
/lgtm

I can't approve since I'm on on the list (which probably needs updating):

https://github.com/openshift/cluster-olm-operator/blob/dac19dbfc9a1b0c93cc9366dbbef396133c5d7cb/OWNERS_ALIASES#L4-L11

**Comment by grokspawn** [comment]
> /lgtm
> 
> I can't approve since I'm on on the list (which probably needs updating):
> 
> https://github.com/openshift/cluster-olm-operator/blob/dac19dbfc9a1b0c93cc9366dbbef396133c5d7cb/OWNERS_ALIASES#L4-L11

I'd approve that PR.

**Pull request merged**
